version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      # Install prerequisites
      - apt-get update && apt-get install -y jq ca-certificates curl gnupg
      # Set up Docker repository
      - install -m 0755 -d /etc/apt/keyrings
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      - chmod a+r /etc/apt/keyrings/docker.gpg
      - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      # Install Docker
      - apt-get update
      - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      - nohup dockerd &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - REPOSITORY_URI=$DOCKERHUB_USERNAME/$DOCKER_REPO_NAME
      - echo "Logging into DockerHub..."
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to DockerHub..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest

      - echo "Getting current task definition..."
      - echo "Task Family: $TASK_FAMILY"

      # Get and display current task definition
      - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition $TASK_FAMILY --region us-east-2)
      - echo "Current task definition: $TASK_DEFINITION"

      # Create new task definition
      - echo "Creating new task definition..."
      - NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$REPOSITORY_URI:$IMAGE_TAG" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)')
      - echo "New task definition JSON: $NEW_TASK_DEFINITION"

      # Register new task definition
      - echo "Registering new task definition..."
      - NEW_TASK_INFO=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION" --region us-east-2)
      - echo "New task info: $NEW_TASK_INFO"

      # Extract revision number and verify it
      - NEW_REVISION=$(echo $NEW_TASK_INFO | jq -r '.taskDefinition.revision')
      - echo "New revision number: $NEW_REVISION"

      # Update service with explicit task definition
      - echo "Updating ECS service with task definition $TASK_FAMILY:$NEW_REVISION..."
      - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition "$TASK_FAMILY:$NEW_REVISION" --force-new-deployment --region us-east-2
      - echo "Service update completed"

artifacts:
  files: []
