version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing Docker..."
      - apt-get update
      - apt-get install -y ca-certificates curl gnupg
      - install -m 0755 -d /etc/apt/keyrings
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      - chmod a+r /etc/apt/keyrings/docker.gpg
      - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      - apt-get update
      - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
      - docker --version

  pre_build:
    commands:
      - echo "Configuring Docker..."
      - nohup dockerd &
      - sleep 5
      - docker info

  build:
    commands:
      - echo "Starting build..."
      - docker compose build

  post_build:
    commands:
      - echo "Deploying to Lightsail..."
      - mkdir -p ~/.ssh

      # Retrieve the private key from Secrets Manager and write to file
      - aws secretsmanager get-secret-value --secret-id CodeBuildLightsailSSHKey --query SecretString --output text > ~/.ssh/id_ed25519

      - chmod 600 ~/.ssh/id_ed25519

      # Deploy
      - scp -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no docker-compose.yml ${LIGHTSAIL_USERNAME}@${LIGHTSAIL_HOST}:~/caderneta/
      - scp -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no Dockerfile ${LIGHTSAIL_USERNAME}@${LIGHTSAIL_HOST}:~/caderneta/
      - |
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${LIGHTSAIL_USERNAME}@${LIGHTSAIL_HOST} << 'EOF'
          cd ~/caderneta
          docker compose down
          docker compose pull
          docker compose up -d
          docker image prune -f
        EOF

      # Clean up
      - rm -rf ~/.ssh

artifacts:
  files:
    - docker-compose.yml
    - Dockerfile
    - '**/*'
