version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Instalando Docker..."
      - sudo rm -r /var/cache/dnf
      - dnf update -y
      - dnf install -y docker

  pre_build:
    commands:
      - echo "Configurando Docker..."
      - systemctl start docker || true
      - usermod -a -G docker $USER
      - chmod 666 /var/run/docker.sock

  build:
    commands:
      - docker compose build

  post_build:
    commands:
      # Deploy to Lightsail instance
      - echo "Deploying to Lightsail..."
      - echo "${LIGHTSAIL_SSH_PRIVATE_KEY}" > id_ed25519
      - chmod 600 id_ed25519

      # Copy docker-compose and deploy
      - scp -i id_ed25519 -o StrictHostKeyChecking=no docker-compose.yml ${LIGHTSAIL_USERNAME}@${LIGHTSAIL_HOST}:~/caderneta
      - scp -i id_ed25519 -o StrictHostKeyChecking=no Dockerfile ${LIGHTSAIL_USERNAME}@${LIGHTSAIL_HOST}:~/caderneta
      - |
        ssh -i id_ed25519 StrictHostKeyChecking=no ${LIGHTSAIL_USERNAME}@${LIGHTSAIL_HOST} << 'EOF'
          # Pull and restart containers
          cd ~/caderneta

          docker compose down

          docker compose up -d

          docker image prune -f
        EOF

      # Clean up sensitive files
      - rm id_ed25519
