services:
  db:
    image: postgres:16-alpine3.20
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - caderneta_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  cache:
    image: redis:7.4-alpine3.20
    ports:
      - '6379:6379'
    volumes:
      - caderneta_redis_data:/data

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: poetry run alembic upgrade head
    restart: "no"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - /opt/caderneta/static:/opt/caderneta/static
    restart: unless-stopped

volumes:
  caderneta_postgres_data:
  caderneta_redis_data:
