services:
  db:
    image: postgres:16-alpine3.20
    env_file:
      - .env
    network_mode: host
    volumes:
      - caderneta_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: no

  cache:
    image: redis:7.4-alpine3.20
    network_mode: host
    volumes:
      - caderneta_redis_data:/data

volumes:
  caderneta_postgres_data:
  caderneta_redis_data:
