services:
  db:
    image: postgres:16-alpine3.20
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - caderneta-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7.4-alpine3.20
    ports:
      - '6379:6379'
    volumes:
      - caderneta-cache:/data

volumes:
    caderneta-data:
    caderneta-cache:
