"""cria tabelas iniciais

Revision ID: 023fdc7372f5
Revises: 0ec4f9ffac62
Create Date: 2024-09-25 21:32:54.010374

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.dominio.transacao.tipos import TipoTransacaoORM

# revision identifiers, used by Alembic.
revision: str = "023fdc7372f5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=True),
        sa.Column("sobrenome", sa.String(), nullable=True),
        sa.Column("telefone", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("senha", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_id"), "usuarios", ["id"], unique=False)
    op.create_table(
        "transacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column("valor", sa.Float(), nullable=True),
        sa.Column("destino", sa.String(), nullable=True),
        sa.Column("tipo", TipoTransacaoORM(), nullable=True),
        sa.Column("descricao", sa.String(), nullable=True),
        sa.Column("caixa", sa.DateTime(), nullable=True),
        sa.Column("competencia", sa.DateTime(), nullable=True),
        sa.Column("apagado", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transacoes_id"), "transacoes", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transacoes_id"), table_name="transacoes")
    op.drop_table("transacoes")
    op.drop_index(op.f("ix_usuarios_id"), table_name="usuarios")
    op.drop_table("usuarios")
    # ### end Alembic commands ###
