"""adiciona tabela assinatuas

Revision ID: 593687b0758d
Revises: 5fc814d354fe
Create Date: 2024-11-26 23:03:45.596990

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "593687b0758d"
down_revision: Union[str, None] = "5fc814d354fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assinaturas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column("plano", sa.String(), nullable=True),
        sa.Column("valor_mensal", sa.Float(), nullable=True),
        sa.Column("data_inicio", sa.DateTime(), nullable=True),
        sa.Column("data_termino", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ATIVA", "CANCELADA", "PENDENTE", "EXPIRADA", "TESTE", name="statusassinatura"),
            nullable=True,
        ),
        sa.Column("data_proximo_pagamento", sa.Date(), nullable=True),
        sa.Column("data_ultimo_pagamento", sa.Date(), nullable=True),
        sa.Column("renovacao_automatica", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("usuario_id"),
    )
    op.create_index(op.f("ix_assinaturas_id"), "assinaturas", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assinaturas_id"), table_name="assinaturas")
    op.drop_table("assinaturas")
    # ### end Alembic commands ###
