"""cria coluna destino

Revision ID: 739dfe8247d0
Revises: 9b0b3d9c8f73
Create Date: 2025-05-05 21:53:13.623928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "739dfe8247d0"
down_revision: Union[str, None] = "9b0b3d9c8f73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transacoes", sa.Column("destino", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transacoes", "destino")
    # ### end Alembic commands ###
