"""cria tabelas iniciais

Revision ID: 9b0b3d9c8f73
Revises:
Create Date: 2025-02-04 00:20:58.289657

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.dominio.transacao.tipos import TipoTransacaoORM

# revision identifiers, used by Alembic.
revision: str = "9b0b3d9c8f73"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usuarios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nome", sa.String(), nullable=True),
        sa.Column("sobrenome", sa.String(), nullable=True),
        sa.Column("telefone", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("senha", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assinaturas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stripe_id", sa.String(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=True),
        sa.Column("plano", sa.String(), nullable=True),
        sa.Column("valor_mensal", sa.Float(), nullable=True),
        sa.Column("data_inicio", sa.DateTime(), nullable=True),
        sa.Column("data_termino", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ATIVA", "CANCELADA", "PENDENTE", "EXPIRADA", "TESTE", name="statusassinatura"),
            nullable=True,
        ),
        sa.Column("data_proximo_pagamento", sa.DateTime(), nullable=True),
        sa.Column("data_ultimo_pagamento", sa.DateTime(), nullable=True),
        sa.Column("renovacao_automatica", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_id"),
        sa.UniqueConstraint("usuario_id"),
    )
    op.create_table(
        "transacoes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=True),
        sa.Column("valor", sa.Float(), nullable=True),
        sa.Column("categoria", sa.String(), nullable=True),
        sa.Column("tipo", TipoTransacaoORM(), nullable=True),
        sa.Column("descricao", sa.String(), nullable=True),
        sa.Column("caixa", sa.DateTime(), nullable=True),
        sa.Column("competencia", sa.DateTime(), nullable=True),
        sa.Column("wamid", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transacoes")
    op.drop_table("assinaturas")
    op.drop_table("usuarios")
    # ### end Alembic commands ###
