"""utiliza datetime em vez de date

Revision ID: c91583be52e1
Revises: eaa5645cdc68
Create Date: 2024-11-27 17:40:04.986077

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c91583be52e1"
down_revision: Union[str, None] = "eaa5645cdc68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assinaturas", "data_proximo_pagamento", existing_type=sa.DATE(), type_=sa.DateTime(), existing_nullable=True
    )
    op.alter_column(
        "assinaturas", "data_ultimo_pagamento", existing_type=sa.DATE(), type_=sa.DateTime(), existing_nullable=True
    )
    op.alter_column("transacoes", "wamid", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("transacoes", "wamid", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "assinaturas", "data_ultimo_pagamento", existing_type=sa.DateTime(), type_=sa.DATE(), existing_nullable=True
    )
    op.alter_column(
        "assinaturas", "data_proximo_pagamento", existing_type=sa.DateTime(), type_=sa.DATE(), existing_nullable=True
    )
    # ### end Alembic commands ###
