"""cria tabela de bpo

Revision ID: deb5fed5ceef
Revises: c91583be52e1
Create Date: 2025-01-31 22:09:29.120781

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "deb5fed5ceef"
down_revision: Union[str, None] = "c91583be52e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bpo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=True),
        sa.Column("sobrenome", sa.String(), nullable=True),
        sa.Column("telefone", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("senha", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bpo_id"), "bpo", ["id"], unique=False)
    op.add_column("usuarios", sa.Column("bpo_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "usuarios", "bpo", ["bpo_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "usuarios", type_="foreignkey")
    op.drop_column("usuarios", "bpo_id")
    op.drop_index(op.f("ix_bpo_id"), table_name="bpo")
    op.drop_table("bpo")
    # ### end Alembic commands ###
