name: Caderneta CI/CD
on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Python 3.12.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Wait for PostgreSQL
        run: for i in {1..30}; do pg_isready -h localhost -p 5432 && break || sleep 1; done

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root --with dev

      - name: Run migrations
        env:
          DATABASE_URL: "postgresql://test_user:test_pass@localhost:5432/test_db"
        run: |
          poetry run alembic upgrade head

      - name: Check ruff
        run: |
          make ruff-fix

      - name: Run tests
        env:
          DATABASE_URL: "postgresql://test_user:test_pass@localhost:5432/test_db"
          CADERNETA_URL: http://localhost:8000
          ENV: testing
          PYTHONPATH: ${PWD}
          CSV_TREINAMENTO: tests/parser/test.csv
          CLASSIFIER_PATH: tests/parser/classifier.joblib
          VECTORIZER_PATH: tests/parser/vectorizer.joblib
          FRONT: https://caderneta.tunn.dev
          STATIC_URL: https://caderneta-back.tunn.dev/static
          BUCKET: /tmp/.caderneta-static
        run: |
          poetry run pytest -vv


  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      - name: Login Dockerhub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t lev0x79/caderneta .

      - name: Push Docker image
        run: docker push lev0x79/caderneta

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker compose pull
      - name: Remove old image
        run: docker rm -f caderneta
      - name: Run new docker container
        run: docker compose up --build -d --remove-orphans
